---
kind: pipeline
name: Darknet-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  commands:
  - echo Building on ARM64
  - docker build -t Dockerfile
  - echo Add push to DH here..
