FROM xaoc000/darknet4iofog

RUN git clone https://github.com/Xaoc000/darknet.git

RUN pip3 install --upgrade pip

RUN pip3 install iofog-python-sdk ws4py opencv-python

WORKDIR darknet

RUN if command -v nvcc ; then export GPU=1; else export GPU=0; fi

RUN GPU=$GPU OPENCV=1 CUDNN=$GPU make -j

ENTRYPOINT ["sh", "-c", "python3 darknet_video.py"]